# UV Workspace Configuration - HACS Healthcare Agent Communication Standard
[tool.uv]
dev-dependencies = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "ruff>=0.1.0",
    "mypy>=1.0.0",
    "psycopg[binary]>=3.1.0", # For PostgreSQL with pgvector
    "pre-commit>=3.0.0",
    "pytest-cov>=6.2.1",
    "twine>=4.0.0", # For PyPI publishing
]

[tool.uv.workspace]
members = [
    "packages/hacs-core",
    "packages/hacs-tools",
    "packages/hacs-utils",
    "packages/hacs-persistence",
    "packages/hacs-registry",
    "packages/hacs-cli",
]

[tool.uv.sources]
hacs-core = { workspace = true }
hacs-tools = { workspace = true }
hacs-utils = { workspace = true }
hacs-persistence = { workspace = true }
hacs-registry = { workspace = true }
hacs-cli = { workspace = true }
