[project]
name = "hacs-hf-ingestion"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
  "datasets>=2.19.0",
  # local packages provided via PYTHONPATH or workspace members
  "matplotlib>=3.10.5",
  "pandas>=2.3.1",
  "rich>=14.1.0",
  "seaborn>=0.13.2",
]


