FROM squidfunk/mkdocs-material:latest

# Install required MkDocs plugins for this project
RUN pip install --no-cache-dir "mkdocstrings[python]" mkdocs-mermaid2-plugin

# Default command is provided by base image (entrypoint: mkdocs)

